### ISSUE TITLE
Incorrect delta-times when recording

### ISSUE THREAD

**Issue by samuel-carradice** [melanchall/drywetmidi#103]
I am developing a simple record and playback application. Using the short examples in the documentation, I can record a file from a MIDI keyboard and play back, but the play back speed is wrong. Looking at the raw data, it is clear that the fault is in the recording, not in the play back. All event delta-time values are being saved as single bytes instead of variable length quantities. Do you have any clue as to why this is so?

**Comment by melanchall** [comment]
Hi,

Can you please provide details about the problem?

> Looking at the raw data, it is clear that the fault is in the recording, not in the play back. All event delta-time values are being saved as single bytes instead of variable length quantities.

Saved where? What is raw data? Did you save recorded data to MIDI file and viewed it in hex editor? MIDI file writing always uses VLQ for delta-times, I suppose that's not the root cause of your problem.

**Comment by samuel-carradice** [comment]
This is the code I am using...
            InputDevice _input = InputDevice.GetByName("USB Audio Device");
            Recording _recording = new Recording(TempoMap.Default, _input);
            _input.StartEventsListening();
            _recording.Start();
            ...
            _input.StopEventsListening();
            _recording.Stop();
            MidiFile file = _recording.ToFile();
            _recording.Dispose();
            file.Write("Recorded.mid", true, MidiFileFormat.SingleTrack);

Yes, I am using a Hex Editor to look at the save .mid file. If I play fast notes (i.e. one-byte delta-times) then the play back is correct. If the notes and rests are longer then the play back is fast and irregular because only the least significant byte of the VLQ is being saved to the file.

**Comment by melanchall** [comment]
Hmm, OK thanks for the info. I'll check it and let you know.

**Comment by samuel-carradice** [comment]
Thanks. Here is the HEX output from a short file. I have played two fast notes followed by two long notes, but the delta-times are clearly wrong...

4d 54 68 64 00 00 00 06 00 00 00 01 00 60 4d 54
72 6b 00 00 00 24 22 90 3c 64 13 90 3c 00 17 90
3c 64 16 90 3c 00 1a 90 3c 64 11 90 3c 00 16 90
3c 64 08 90 3c 00 00 ff 2f 00

**Comment by melanchall** [comment]
Provided bytes are indeed represent MIDI file with delta-times that can be packed to one byte. BUT I've created additional unit tests to check that any delta-times are written correctly, and those tests are passed. So the error is not with MIDI file writing.

Well, can you please show me events stored in recording after it's stopped? Just screenshot from Visual Studio in debug. Like this:

![image](https://user-images.githubusercontent.com/26361185/96164545-0611c800-0f24-11eb-912a-8c9899012c70.png)

And please send me the file created from this recoring. So I can compare what's wrong.

**Comment by samuel-carradice** [comment]
I have played a short note, a long rest and a long note. GetEvents returns this...
![Image1](https://user-images.githubusercontent.com/25862706/96167663-a4e3f780-0f17-11eb-8912-d1fc52c36ba5.jpg)

The list includes ActiveSensingEvents which I have filtered out - but the fact I get these may be significant? Disregarding these, the four event appear correct, with delta-time values of 16 for the short note, 526 for the rest and 449 for the long note. I believe these should encode to VLQs 10 (hex), 84 0E and 83 41 respectively.
The hex file is attached...
![Image2](https://user-images.githubusercontent.com/25862706/96167679-a9a8ab80-0f17-11eb-8391-7d7f492a86c4.jpg)
The first time appears correctly at byte 1A, but the other two appear as 27 at byte 1E and 0B at byte 22.

If you can't find something obvious that is wrong then I would be happy to stream the file myself using the GetEvents collection.

**Comment by melanchall** [comment]
@samuel-carradice Can you please leave all events as is, without filtering _ActiveSensingEvents_ and show me new screenshot? And please drop the recorded file to a comment as mid file, not a screenshot with bytes so I can analyze all things by myself.

**Comment by samuel-carradice** [comment]
Certainly. Here is a file with Active Sensing events. There were a couple before the first note event.
![Image3](https://user-images.githubusercontent.com/25862706/96175215-7a4b6c00-0f22-11eb-8417-41bfdf46dd12.jpg)
I see the note events are all shown as "Note On" although they are obviously on and off events.

I couldn't attach the .mid file directly but hopefully it is included in this zip file...
[Recorded.zip](https://github.com/melanchall/drywetmidi/files/5387263/Recorded.zip)

**Comment by melanchall** [comment]
A couple of moments to note:
* I'm sure that Note On events with velocity of zero instead of Note Off ones is a feature of your keyboard. Some keyboards can do it to use running status for events of same type. DryWetMIDI records events as is, without processing. You see exactly what's incoming. I have unit tests that guarantee that events receiving works properly.
* Active Sensing events should not be present in a MIDI file since they are not part of SMF specification. It's a bug and must be fixed so all system real-time and system common events will be filtered out before saving to file.

As for delta-times, I'll check them tomorrow.

**Comment by melanchall** [comment]
Checked it now :) Yes, those Active Sensing events is a root cause of the problem. I'll implement filtering such events and let you know. Thanks for the issue!

**Comment by melanchall** [comment]
I've fixed the issue. MIDI file will not contain events prohibited by SMF specification anymore and delta-times will be correct. Changes are in _develop_ branch. So you can either build the library from sources or take DLL from [DryWetMIDI.5.2.0-bin-net45.zip](https://github.com/melanchall/drywetmidi/files/5393175/DryWetMIDI.5.2.0-bin-net45.zip) or [DryWetMIDI.5.2.0-bin-netstandard20.zip](https://github.com/melanchall/drywetmidi/files/5393177/DryWetMIDI.5.2.0-bin-netstandard20.zip).

Please let me know if it works or not.

**Comment by samuel-carradice** [comment]
I have removed the Nuget package from my VS solution, deleted the existing dll and xml files, downloaded version 5.2.0 for .NET 4.5 from your link, and added a reference to the new dll. I still get Active Sensing Events in the GetEvents collection. I strongly suspect this issue is specific to the keyboard I am using for development, and it may not be a problem with the actual device I am aiming to use, but that is still to be confirmed. In any case, I can work around the problem now that we know what it is.

**Comment by melanchall** [comment]
It's correct that `GetEvents` returns all events. The fix is `ToFile` will produce a MIDI file without undesirable events and thus playback on this file will be correct. Let me know that original problem is solved.

**Comment by samuel-carradice** [comment]
Thanks for the clarification. Sorry I didn't get that far in my test! The problem is fixed. Thanks very much for your prompt response.
